name: Deploy to AWS Lambda via GitHub Actions

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build for Lambda
      run: |
        # Would need significant code restructuring first
        npm run build:lambda
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: us-east-1

    - name: Deploy to Lambda
      uses: aws-actions/aws-lambda-deploy@v1
      with:
        function-name: csc-member-management
        code-artifacts-dir: dist/
        handler: index.handler
        runtime: nodejs20.x
        memory-size: 512
        timeout: 30
        environment-variables: |
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          SESSION_SECRET=${{ secrets.SESSION_SECRET }}
          ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}
          ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}